version: '3.8'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend/data:/app/data
    ports: ["5000:5000"]
  frontend:
    build: ./frontend
    ports: ["8080:80"]
    depends_on: ["backend"]
